apiVersion: v1
kind: ConfigMap
metadata:
  name: grade-submission-portal-config
  namespace: grade-submission  # optional if default
data:
  # Key-value pairs
  GRADE_SERVICE_HOST: "grade-submission-api"