apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: grade-submission
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: grade-submission-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1 ## ensure that we do not have more than 3 pod replicas
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grade-submission
        app.kubernetes.io/components: backend
        app.kubernetes.io/instance: grade-submission-api
    spec:
      containers:
        - name: grade-submission-api
          # image: rslim087/kubernetes-course-grade-submission-api:stateless-v2
          image: rslim087/kubernetes-course-grade-submission-api:stateless-v3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: grade-submission-api-config
            - secretRef:
                name: grade-submission-api-secret
          resources:
            requests: 
              memory: "256Mi"
              cpu: "128m"
            limits:
              memory: "512Mi"
          ports:
            - containerPort: 3001
